language: ruby
before_install:
  - "rm -f ${BUNDLE_GEMFILE}.lock"
  - "travis_retry gem update --system"
  - "travis_retry gem install bundler -N"
script: rake
install: bundle install
rvm:
  - 2.4.4
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby-head
