---
name: CI

# https://github.com/actions/virtual-environments#available-environments
# https://github.com/ruby/setup-ruby/blob/master/README.md#supported-platforms

on:
  push:
    branches:
      - master
      - main

jobs:
  test:
    name: >-
      test ${{ matrix.os }} ${{ matrix.ruby }}

    runs-on: ${{ matrix.os }}
    if: |
      !(   contains(github.event.pull_request.title,  '[ci skip]')
        || contains(github.event.pull_request.title,  '[skip ci]'))
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
        ruby:
          - '2.4'
          - '2.5'
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
        # include:
        #   - os: windows-latest
        #     ruby: ruby

    steps:
      - name: repo checkout
        uses: actions/checkout@v2

      - name: load ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: test
        run: bundle exec rake
        timeout-minutes: 3
